// <auto-generated />
using System;
using DepoYonetim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepoYonetim.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DepoYonetim.Models.Depo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FabrikaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FabrikaId");

                    b.ToTable("Depolar");
                });

            modelBuilder.Entity("DepoYonetim.Models.Fabrika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fabrikalar");
                });

            modelBuilder.Entity("DepoYonetim.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("DepoYonetim.Models.Raf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.ToTable("Raflar");
                });

            modelBuilder.Entity("DepoYonetim.Models.RafStok", b =>
                {
                    b.Property<int>("RafId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.HasKey("RafId", "UrunId");

                    b.HasIndex("UrunId");

                    b.ToTable("RafStoklari");
                });

            modelBuilder.Entity("DepoYonetim.Models.StokHareketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RafId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("RafId");

                    b.HasIndex("UrunId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("DepoYonetim.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barkod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("DepoYonetim.Models.Depo", b =>
                {
                    b.HasOne("DepoYonetim.Models.Fabrika", "Fabrika")
                        .WithMany("Depolar")
                        .HasForeignKey("FabrikaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabrika");
                });

            modelBuilder.Entity("DepoYonetim.Models.Raf", b =>
                {
                    b.HasOne("DepoYonetim.Models.Depo", "Depo")
                        .WithMany("Raflar")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depo");
                });

            modelBuilder.Entity("DepoYonetim.Models.RafStok", b =>
                {
                    b.HasOne("DepoYonetim.Models.Raf", "Raf")
                        .WithMany("Stoklar")
                        .HasForeignKey("RafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetim.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raf");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("DepoYonetim.Models.StokHareketi", b =>
                {
                    b.HasOne("DepoYonetim.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetim.Models.Raf", "Raf")
                        .WithMany()
                        .HasForeignKey("RafId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DepoYonetim.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Raf");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("DepoYonetim.Models.Depo", b =>
                {
                    b.Navigation("Raflar");
                });

            modelBuilder.Entity("DepoYonetim.Models.Fabrika", b =>
                {
                    b.Navigation("Depolar");
                });

            modelBuilder.Entity("DepoYonetim.Models.Raf", b =>
                {
                    b.Navigation("Stoklar");
                });
#pragma warning restore 612, 618
        }
    }
}
